# Generated by Django 3.1.1 on 2022-06-28 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_auto_20220627_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categorii'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentariu', 'verbose_name_plural': 'Comentarii'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Imagine', 'verbose_name_plural': 'Imagini'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proiect', 'verbose_name_plural': 'Proiecte'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Citat', 'verbose_name_plural': 'Citate'},
        ),
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.project', verbose_name='Proiect'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=400, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=150, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Imagine'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Principală'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.project', verbose_name='Proiect'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.project', verbose_name='Proiect'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Citat'),
        ),
    ]
