# Generated by Django 3.1.1 on 2023-03-30 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0003_auto_20220628_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titlu')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.category', verbose_name='Categorie')),
                ('tags', models.ManyToManyField(to='portofolio.Tag')),
            ],
        ),
    ]
